"""Add blockchain tasks table

Revision ID: 0f223737026c
Revises: 4563cc017e22
Create Date: 2026-07-08 06:46:39.854222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f223737026c'
down_revision: Union[str, Sequence[str], None] = '4563cc017e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'blockchain_audit_logs' not in tables:
        op.create_table('blockchain_audit_logs',
        sa.Column('transaction_hash', sa.String(length=66), nullable=False),
        sa.Column('block_number', sa.Integer(), nullable=True),
        sa.Column('gas_used', sa.Integer(), nullable=True),
        sa.Column('wallet_address', sa.String(length=42), nullable=True),
        sa.Column('contract_address', sa.String(length=42), nullable=True),
        sa.Column('chain_id', sa.Integer(), nullable=True),
        sa.Column('explorer_url', sa.String(length=255), nullable=True),
        sa.Column('confirmation_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failure_reason', sa.Text(), nullable=True),
        sa.Column('prescription_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('transaction_hash')
        )
    if 'blockchain_tasks' not in tables:
        op.create_table('blockchain_tasks',
        sa.Column('prescription_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'CONFIRMED', 'FAILED', 'RETRYING', 'CANCELLED', name='blockchaintaskstatus'), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('next_retry_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('prescription_id')
        )
    op.execute("ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS blockchain_status VARCHAR(50)")
    op.execute("ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS blockchain_tx_hash VARCHAR(66)")
    op.execute("ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS block_number INTEGER")
    op.execute("ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS hash VARCHAR(64)")
    op.execute("ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1")
    op.execute("ALTER TABLE prescriptions ADD COLUMN IF NOT EXISTS registered_at VARCHAR")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'registered_at')
    op.drop_column('prescriptions', 'version')
    op.drop_column('prescriptions', 'hash')
    op.drop_column('prescriptions', 'block_number')
    op.drop_column('prescriptions', 'blockchain_tx_hash')
    op.drop_column('prescriptions', 'blockchain_status')
    op.drop_table('blockchain_tasks')
    op.drop_table('blockchain_audit_logs')
    # ### end Alembic commands ###
