"""Add pharmacy_restock_orders table

Revision ID: f1e2d3c4b5a6
Revises: bb2f70762e6f
Create Date: 2026-09-12 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = 'f1e2d3c4b5a6'
down_revision = 'bb2f70762e6f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_restock_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expected_delivery', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_restock_orders_created_at'), 'pharmacy_restock_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_pharmacy_restock_orders_expected_delivery'), 'pharmacy_restock_orders', ['expected_delivery'], unique=False)
    op.create_index(op.f('ix_pharmacy_restock_orders_id'), 'pharmacy_restock_orders', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_restock_orders_medicine_id'), 'pharmacy_restock_orders', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_restock_orders_pharmacy_id'), 'pharmacy_restock_orders', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_restock_orders_status'), 'pharmacy_restock_orders', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_restock_orders_status'), table_name='pharmacy_restock_orders')
    op.drop_index(op.f('ix_pharmacy_restock_orders_pharmacy_id'), table_name='pharmacy_restock_orders')
    op.drop_index(op.f('ix_pharmacy_restock_orders_medicine_id'), table_name='pharmacy_restock_orders')
    op.drop_index(op.f('ix_pharmacy_restock_orders_id'), table_name='pharmacy_restock_orders')
    op.drop_index(op.f('ix_pharmacy_restock_orders_expected_delivery'), table_name='pharmacy_restock_orders')
    op.drop_index(op.f('ix_pharmacy_restock_orders_created_at'), table_name='pharmacy_restock_orders')
    op.drop_table('pharmacy_restock_orders')
    # ### end Alembic commands ###
