/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDoctorRegistry {
  export type DoctorStruct = {
    licenseHash: BytesLike;
    hospitalHash: BytesLike;
    wallet: AddressLike;
    createdTimestamp: BigNumberish;
    updatedTimestamp: BigNumberish;
    isVerified: boolean;
    isActive: boolean;
  };

  export type DoctorStructOutput = [
    licenseHash: string,
    hospitalHash: string,
    wallet: string,
    createdTimestamp: bigint,
    updatedTimestamp: bigint,
    isVerified: boolean,
    isActive: boolean
  ] & {
    licenseHash: string;
    hospitalHash: string;
    wallet: string;
    createdTimestamp: bigint;
    updatedTimestamp: bigint;
    isVerified: boolean;
    isActive: boolean;
  };
}

export interface DoctorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "doctors"
      | "getDoctor"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "pause"
      | "paused"
      | "reactivateDoctor"
      | "registerDoctor"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "suspendDoctor"
      | "unpause"
      | "updateAffiliation"
      | "verifyDoctor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DoctorAffiliationUpdated"
      | "DoctorReactivated"
      | "DoctorRegistered"
      | "DoctorSuspended"
      | "DoctorVerified"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "doctors", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getDoctor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateDoctor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDoctor",
    values: [BytesLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendDoctor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAffiliation",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDoctor",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doctors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDoctor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAffiliation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDoctor",
    data: BytesLike
  ): Result;
}

export namespace DoctorAffiliationUpdatedEvent {
  export type InputTuple = [
    doctorHash: BytesLike,
    newHospitalHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    doctorHash: string,
    newHospitalHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    doctorHash: string;
    newHospitalHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorReactivatedEvent {
  export type InputTuple = [doctorHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [doctorHash: string, timestamp: bigint];
  export interface OutputObject {
    doctorHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorRegisteredEvent {
  export type InputTuple = [
    doctorHash: BytesLike,
    licenseHash: BytesLike,
    wallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    doctorHash: string,
    licenseHash: string,
    wallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    doctorHash: string;
    licenseHash: string;
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorSuspendedEvent {
  export type InputTuple = [doctorHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [doctorHash: string, timestamp: bigint];
  export interface OutputObject {
    doctorHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorVerifiedEvent {
  export type InputTuple = [doctorHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [doctorHash: string, timestamp: bigint];
  export interface OutputObject {
    doctorHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DoctorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DoctorRegistry;
  waitForDeployment(): Promise<this>;

  interface: DoctorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  doctors: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        licenseHash: string;
        hospitalHash: string;
        wallet: string;
        createdTimestamp: bigint;
        updatedTimestamp: bigint;
        isVerified: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getDoctor: TypedContractMethod<
    [doctorHash: BytesLike],
    [IDoctorRegistry.DoctorStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  reactivateDoctor: TypedContractMethod<
    [doctorHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerDoctor: TypedContractMethod<
    [
      doctorHash: BytesLike,
      licenseHash: BytesLike,
      hospitalHash: BytesLike,
      wallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  suspendDoctor: TypedContractMethod<
    [doctorHash: BytesLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateAffiliation: TypedContractMethod<
    [doctorHash: BytesLike, newHospitalHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyDoctor: TypedContractMethod<
    [doctorHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "doctors"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        licenseHash: string;
        hospitalHash: string;
        wallet: string;
        createdTimestamp: bigint;
        updatedTimestamp: bigint;
        isVerified: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDoctor"
  ): TypedContractMethod<
    [doctorHash: BytesLike],
    [IDoctorRegistry.DoctorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "reactivateDoctor"
  ): TypedContractMethod<[doctorHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerDoctor"
  ): TypedContractMethod<
    [
      doctorHash: BytesLike,
      licenseHash: BytesLike,
      hospitalHash: BytesLike,
      wallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "suspendDoctor"
  ): TypedContractMethod<[doctorHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAffiliation"
  ): TypedContractMethod<
    [doctorHash: BytesLike, newHospitalHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDoctor"
  ): TypedContractMethod<[doctorHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "DoctorAffiliationUpdated"
  ): TypedContractEvent<
    DoctorAffiliationUpdatedEvent.InputTuple,
    DoctorAffiliationUpdatedEvent.OutputTuple,
    DoctorAffiliationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DoctorReactivated"
  ): TypedContractEvent<
    DoctorReactivatedEvent.InputTuple,
    DoctorReactivatedEvent.OutputTuple,
    DoctorReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "DoctorRegistered"
  ): TypedContractEvent<
    DoctorRegisteredEvent.InputTuple,
    DoctorRegisteredEvent.OutputTuple,
    DoctorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DoctorSuspended"
  ): TypedContractEvent<
    DoctorSuspendedEvent.InputTuple,
    DoctorSuspendedEvent.OutputTuple,
    DoctorSuspendedEvent.OutputObject
  >;
  getEvent(
    key: "DoctorVerified"
  ): TypedContractEvent<
    DoctorVerifiedEvent.InputTuple,
    DoctorVerifiedEvent.OutputTuple,
    DoctorVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DoctorAffiliationUpdated(bytes32,bytes32,uint256)": TypedContractEvent<
      DoctorAffiliationUpdatedEvent.InputTuple,
      DoctorAffiliationUpdatedEvent.OutputTuple,
      DoctorAffiliationUpdatedEvent.OutputObject
    >;
    DoctorAffiliationUpdated: TypedContractEvent<
      DoctorAffiliationUpdatedEvent.InputTuple,
      DoctorAffiliationUpdatedEvent.OutputTuple,
      DoctorAffiliationUpdatedEvent.OutputObject
    >;

    "DoctorReactivated(bytes32,uint256)": TypedContractEvent<
      DoctorReactivatedEvent.InputTuple,
      DoctorReactivatedEvent.OutputTuple,
      DoctorReactivatedEvent.OutputObject
    >;
    DoctorReactivated: TypedContractEvent<
      DoctorReactivatedEvent.InputTuple,
      DoctorReactivatedEvent.OutputTuple,
      DoctorReactivatedEvent.OutputObject
    >;

    "DoctorRegistered(bytes32,bytes32,address,uint256)": TypedContractEvent<
      DoctorRegisteredEvent.InputTuple,
      DoctorRegisteredEvent.OutputTuple,
      DoctorRegisteredEvent.OutputObject
    >;
    DoctorRegistered: TypedContractEvent<
      DoctorRegisteredEvent.InputTuple,
      DoctorRegisteredEvent.OutputTuple,
      DoctorRegisteredEvent.OutputObject
    >;

    "DoctorSuspended(bytes32,uint256)": TypedContractEvent<
      DoctorSuspendedEvent.InputTuple,
      DoctorSuspendedEvent.OutputTuple,
      DoctorSuspendedEvent.OutputObject
    >;
    DoctorSuspended: TypedContractEvent<
      DoctorSuspendedEvent.InputTuple,
      DoctorSuspendedEvent.OutputTuple,
      DoctorSuspendedEvent.OutputObject
    >;

    "DoctorVerified(bytes32,uint256)": TypedContractEvent<
      DoctorVerifiedEvent.InputTuple,
      DoctorVerifiedEvent.OutputTuple,
      DoctorVerifiedEvent.OutputObject
    >;
    DoctorVerified: TypedContractEvent<
      DoctorVerifiedEvent.InputTuple,
      DoctorVerifiedEvent.OutputTuple,
      DoctorVerifiedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
