/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuditTrail } from "./AuditTrail";
export type { DoctorRegistry } from "./DoctorRegistry";
export type { MedicalRecordRegistry } from "./MedicalRecordRegistry";
export type { PatientRegistry } from "./PatientRegistry";
export type { PharmacyRegistry } from "./PharmacyRegistry";
export type { PrescriptionRegistry } from "./PrescriptionRegistry";
