/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPatientRegistry {
  export type PatientStruct = {
    wallet: AddressLike;
    createdTimestamp: BigNumberish;
    updatedTimestamp: BigNumberish;
    isVerified: boolean;
    isActive: boolean;
  };

  export type PatientStructOutput = [
    wallet: string,
    createdTimestamp: bigint,
    updatedTimestamp: bigint,
    isVerified: boolean,
    isActive: boolean
  ] & {
    wallet: string;
    createdTimestamp: bigint;
    updatedTimestamp: bigint;
    isVerified: boolean;
    isActive: boolean;
  };
}

export interface PatientRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "deactivatePatient"
      | "getPatient"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "patients"
      | "pause"
      | "paused"
      | "reactivatePatient"
      | "registerPatient"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "unpause"
      | "updateWallet"
      | "verifyPatient"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PatientDeactivated"
      | "PatientReactivated"
      | "PatientRegistered"
      | "PatientVerified"
      | "PatientWalletUpdated"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivatePatient",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatient",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "patients", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivatePatient",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPatient",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateWallet",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPatient",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivatePatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPatient", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "patients", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivatePatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPatient",
    data: BytesLike
  ): Result;
}

export namespace PatientDeactivatedEvent {
  export type InputTuple = [patientHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [patientHash: string, timestamp: bigint];
  export interface OutputObject {
    patientHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientReactivatedEvent {
  export type InputTuple = [patientHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [patientHash: string, timestamp: bigint];
  export interface OutputObject {
    patientHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientRegisteredEvent {
  export type InputTuple = [
    patientHash: BytesLike,
    wallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patientHash: string,
    wallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patientHash: string;
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientVerifiedEvent {
  export type InputTuple = [patientHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [patientHash: string, timestamp: bigint];
  export interface OutputObject {
    patientHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientWalletUpdatedEvent {
  export type InputTuple = [
    patientHash: BytesLike,
    newWallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patientHash: string,
    newWallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patientHash: string;
    newWallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PatientRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PatientRegistry;
  waitForDeployment(): Promise<this>;

  interface: PatientRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  deactivatePatient: TypedContractMethod<
    [patientHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getPatient: TypedContractMethod<
    [patientHash: BytesLike],
    [IPatientRegistry.PatientStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  patients: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, boolean] & {
        wallet: string;
        createdTimestamp: bigint;
        updatedTimestamp: bigint;
        isVerified: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  reactivatePatient: TypedContractMethod<
    [patientHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerPatient: TypedContractMethod<
    [patientHash: BytesLike, wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateWallet: TypedContractMethod<
    [patientHash: BytesLike, newWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyPatient: TypedContractMethod<
    [patientHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deactivatePatient"
  ): TypedContractMethod<[patientHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPatient"
  ): TypedContractMethod<
    [patientHash: BytesLike],
    [IPatientRegistry.PatientStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "patients"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, boolean] & {
        wallet: string;
        createdTimestamp: bigint;
        updatedTimestamp: bigint;
        isVerified: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "reactivatePatient"
  ): TypedContractMethod<[patientHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerPatient"
  ): TypedContractMethod<
    [patientHash: BytesLike, wallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWallet"
  ): TypedContractMethod<
    [patientHash: BytesLike, newWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyPatient"
  ): TypedContractMethod<[patientHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "PatientDeactivated"
  ): TypedContractEvent<
    PatientDeactivatedEvent.InputTuple,
    PatientDeactivatedEvent.OutputTuple,
    PatientDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PatientReactivated"
  ): TypedContractEvent<
    PatientReactivatedEvent.InputTuple,
    PatientReactivatedEvent.OutputTuple,
    PatientReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PatientRegistered"
  ): TypedContractEvent<
    PatientRegisteredEvent.InputTuple,
    PatientRegisteredEvent.OutputTuple,
    PatientRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PatientVerified"
  ): TypedContractEvent<
    PatientVerifiedEvent.InputTuple,
    PatientVerifiedEvent.OutputTuple,
    PatientVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "PatientWalletUpdated"
  ): TypedContractEvent<
    PatientWalletUpdatedEvent.InputTuple,
    PatientWalletUpdatedEvent.OutputTuple,
    PatientWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "PatientDeactivated(bytes32,uint256)": TypedContractEvent<
      PatientDeactivatedEvent.InputTuple,
      PatientDeactivatedEvent.OutputTuple,
      PatientDeactivatedEvent.OutputObject
    >;
    PatientDeactivated: TypedContractEvent<
      PatientDeactivatedEvent.InputTuple,
      PatientDeactivatedEvent.OutputTuple,
      PatientDeactivatedEvent.OutputObject
    >;

    "PatientReactivated(bytes32,uint256)": TypedContractEvent<
      PatientReactivatedEvent.InputTuple,
      PatientReactivatedEvent.OutputTuple,
      PatientReactivatedEvent.OutputObject
    >;
    PatientReactivated: TypedContractEvent<
      PatientReactivatedEvent.InputTuple,
      PatientReactivatedEvent.OutputTuple,
      PatientReactivatedEvent.OutputObject
    >;

    "PatientRegistered(bytes32,address,uint256)": TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;
    PatientRegistered: TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;

    "PatientVerified(bytes32,uint256)": TypedContractEvent<
      PatientVerifiedEvent.InputTuple,
      PatientVerifiedEvent.OutputTuple,
      PatientVerifiedEvent.OutputObject
    >;
    PatientVerified: TypedContractEvent<
      PatientVerifiedEvent.InputTuple,
      PatientVerifiedEvent.OutputTuple,
      PatientVerifiedEvent.OutputObject
    >;

    "PatientWalletUpdated(bytes32,address,uint256)": TypedContractEvent<
      PatientWalletUpdatedEvent.InputTuple,
      PatientWalletUpdatedEvent.OutputTuple,
      PatientWalletUpdatedEvent.OutputObject
    >;
    PatientWalletUpdated: TypedContractEvent<
      PatientWalletUpdatedEvent.InputTuple,
      PatientWalletUpdatedEvent.OutputTuple,
      PatientWalletUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
