/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAuditTrailInterface extends Interface {
  getFunction(nameOrSignature: "logEvent"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AuditEventLogged"): EventFragment;

  encodeFunctionData(
    functionFragment: "logEvent",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "logEvent", data: BytesLike): Result;
}

export namespace AuditEventLoggedEvent {
  export type InputTuple = [
    eventType: BytesLike,
    entityHash: BytesLike,
    caller: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    eventType: string,
    entityHash: string,
    caller: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    eventType: string;
    entityHash: string;
    caller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAuditTrail extends BaseContract {
  connect(runner?: ContractRunner | null): IAuditTrail;
  waitForDeployment(): Promise<this>;

  interface: IAuditTrailInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  logEvent: TypedContractMethod<
    [eventType: BytesLike, entityHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "logEvent"
  ): TypedContractMethod<
    [eventType: BytesLike, entityHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuditEventLogged"
  ): TypedContractEvent<
    AuditEventLoggedEvent.InputTuple,
    AuditEventLoggedEvent.OutputTuple,
    AuditEventLoggedEvent.OutputObject
  >;

  filters: {
    "AuditEventLogged(bytes32,bytes32,address,uint256)": TypedContractEvent<
      AuditEventLoggedEvent.InputTuple,
      AuditEventLoggedEvent.OutputTuple,
      AuditEventLoggedEvent.OutputObject
    >;
    AuditEventLogged: TypedContractEvent<
      AuditEventLoggedEvent.InputTuple,
      AuditEventLoggedEvent.OutputTuple,
      AuditEventLoggedEvent.OutputObject
    >;
  };
}
