/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDoctorRegistry {
  export type DoctorStruct = {
    licenseHash: BytesLike;
    hospitalHash: BytesLike;
    wallet: AddressLike;
    createdTimestamp: BigNumberish;
    updatedTimestamp: BigNumberish;
    isVerified: boolean;
    isActive: boolean;
  };

  export type DoctorStructOutput = [
    licenseHash: string,
    hospitalHash: string,
    wallet: string,
    createdTimestamp: bigint,
    updatedTimestamp: bigint,
    isVerified: boolean,
    isActive: boolean
  ] & {
    licenseHash: string;
    hospitalHash: string;
    wallet: string;
    createdTimestamp: bigint;
    updatedTimestamp: bigint;
    isVerified: boolean;
    isActive: boolean;
  };
}

export interface IDoctorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getDoctor"
      | "reactivateDoctor"
      | "registerDoctor"
      | "suspendDoctor"
      | "updateAffiliation"
      | "verifyDoctor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DoctorAffiliationUpdated"
      | "DoctorReactivated"
      | "DoctorRegistered"
      | "DoctorSuspended"
      | "DoctorVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getDoctor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateDoctor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDoctor",
    values: [BytesLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendDoctor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAffiliation",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDoctor",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getDoctor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAffiliation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDoctor",
    data: BytesLike
  ): Result;
}

export namespace DoctorAffiliationUpdatedEvent {
  export type InputTuple = [
    doctorHash: BytesLike,
    newHospitalHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    doctorHash: string,
    newHospitalHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    doctorHash: string;
    newHospitalHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorReactivatedEvent {
  export type InputTuple = [doctorHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [doctorHash: string, timestamp: bigint];
  export interface OutputObject {
    doctorHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorRegisteredEvent {
  export type InputTuple = [
    doctorHash: BytesLike,
    licenseHash: BytesLike,
    wallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    doctorHash: string,
    licenseHash: string,
    wallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    doctorHash: string;
    licenseHash: string;
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorSuspendedEvent {
  export type InputTuple = [doctorHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [doctorHash: string, timestamp: bigint];
  export interface OutputObject {
    doctorHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorVerifiedEvent {
  export type InputTuple = [doctorHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [doctorHash: string, timestamp: bigint];
  export interface OutputObject {
    doctorHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDoctorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IDoctorRegistry;
  waitForDeployment(): Promise<this>;

  interface: IDoctorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDoctor: TypedContractMethod<
    [doctorHash: BytesLike],
    [IDoctorRegistry.DoctorStructOutput],
    "view"
  >;

  reactivateDoctor: TypedContractMethod<
    [doctorHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerDoctor: TypedContractMethod<
    [
      doctorHash: BytesLike,
      licenseHash: BytesLike,
      hospitalHash: BytesLike,
      wallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  suspendDoctor: TypedContractMethod<
    [doctorHash: BytesLike],
    [void],
    "nonpayable"
  >;

  updateAffiliation: TypedContractMethod<
    [doctorHash: BytesLike, newHospitalHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyDoctor: TypedContractMethod<
    [doctorHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDoctor"
  ): TypedContractMethod<
    [doctorHash: BytesLike],
    [IDoctorRegistry.DoctorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivateDoctor"
  ): TypedContractMethod<[doctorHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerDoctor"
  ): TypedContractMethod<
    [
      doctorHash: BytesLike,
      licenseHash: BytesLike,
      hospitalHash: BytesLike,
      wallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "suspendDoctor"
  ): TypedContractMethod<[doctorHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAffiliation"
  ): TypedContractMethod<
    [doctorHash: BytesLike, newHospitalHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDoctor"
  ): TypedContractMethod<[doctorHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "DoctorAffiliationUpdated"
  ): TypedContractEvent<
    DoctorAffiliationUpdatedEvent.InputTuple,
    DoctorAffiliationUpdatedEvent.OutputTuple,
    DoctorAffiliationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DoctorReactivated"
  ): TypedContractEvent<
    DoctorReactivatedEvent.InputTuple,
    DoctorReactivatedEvent.OutputTuple,
    DoctorReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "DoctorRegistered"
  ): TypedContractEvent<
    DoctorRegisteredEvent.InputTuple,
    DoctorRegisteredEvent.OutputTuple,
    DoctorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DoctorSuspended"
  ): TypedContractEvent<
    DoctorSuspendedEvent.InputTuple,
    DoctorSuspendedEvent.OutputTuple,
    DoctorSuspendedEvent.OutputObject
  >;
  getEvent(
    key: "DoctorVerified"
  ): TypedContractEvent<
    DoctorVerifiedEvent.InputTuple,
    DoctorVerifiedEvent.OutputTuple,
    DoctorVerifiedEvent.OutputObject
  >;

  filters: {
    "DoctorAffiliationUpdated(bytes32,bytes32,uint256)": TypedContractEvent<
      DoctorAffiliationUpdatedEvent.InputTuple,
      DoctorAffiliationUpdatedEvent.OutputTuple,
      DoctorAffiliationUpdatedEvent.OutputObject
    >;
    DoctorAffiliationUpdated: TypedContractEvent<
      DoctorAffiliationUpdatedEvent.InputTuple,
      DoctorAffiliationUpdatedEvent.OutputTuple,
      DoctorAffiliationUpdatedEvent.OutputObject
    >;

    "DoctorReactivated(bytes32,uint256)": TypedContractEvent<
      DoctorReactivatedEvent.InputTuple,
      DoctorReactivatedEvent.OutputTuple,
      DoctorReactivatedEvent.OutputObject
    >;
    DoctorReactivated: TypedContractEvent<
      DoctorReactivatedEvent.InputTuple,
      DoctorReactivatedEvent.OutputTuple,
      DoctorReactivatedEvent.OutputObject
    >;

    "DoctorRegistered(bytes32,bytes32,address,uint256)": TypedContractEvent<
      DoctorRegisteredEvent.InputTuple,
      DoctorRegisteredEvent.OutputTuple,
      DoctorRegisteredEvent.OutputObject
    >;
    DoctorRegistered: TypedContractEvent<
      DoctorRegisteredEvent.InputTuple,
      DoctorRegisteredEvent.OutputTuple,
      DoctorRegisteredEvent.OutputObject
    >;

    "DoctorSuspended(bytes32,uint256)": TypedContractEvent<
      DoctorSuspendedEvent.InputTuple,
      DoctorSuspendedEvent.OutputTuple,
      DoctorSuspendedEvent.OutputObject
    >;
    DoctorSuspended: TypedContractEvent<
      DoctorSuspendedEvent.InputTuple,
      DoctorSuspendedEvent.OutputTuple,
      DoctorSuspendedEvent.OutputObject
    >;

    "DoctorVerified(bytes32,uint256)": TypedContractEvent<
      DoctorVerifiedEvent.InputTuple,
      DoctorVerifiedEvent.OutputTuple,
      DoctorVerifiedEvent.OutputObject
    >;
    DoctorVerified: TypedContractEvent<
      DoctorVerifiedEvent.InputTuple,
      DoctorVerifiedEvent.OutputTuple,
      DoctorVerifiedEvent.OutputObject
    >;
  };
}
