/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IMedicalRecordRegistry {
  export type MedicalRecordStruct = {
    patientHash: BytesLike;
    uploader: AddressLike;
    timestamp: BigNumberish;
    version: BigNumberish;
    isVerified: boolean;
  };

  export type MedicalRecordStructOutput = [
    patientHash: string,
    uploader: string,
    timestamp: bigint,
    version: bigint,
    isVerified: boolean
  ] & {
    patientHash: string;
    uploader: string;
    timestamp: bigint;
    version: bigint;
    isVerified: boolean;
  };
}

export interface IMedicalRecordRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRecord"
      | "registerRecord"
      | "updateVersion"
      | "verifyRecord"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RecordRegistered"
      | "RecordVerified"
      | "RecordVersionUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRecord",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVersion",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyRecord",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyRecord",
    data: BytesLike
  ): Result;
}

export namespace RecordRegisteredEvent {
  export type InputTuple = [
    recordHash: BytesLike,
    patientHash: BytesLike,
    uploader: AddressLike,
    version: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordHash: string,
    patientHash: string,
    uploader: string,
    version: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordHash: string;
    patientHash: string;
    uploader: string;
    version: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordVerifiedEvent {
  export type InputTuple = [recordHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [recordHash: string, timestamp: bigint];
  export interface OutputObject {
    recordHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordVersionUpdatedEvent {
  export type InputTuple = [
    oldRecordHash: BytesLike,
    newRecordHash: BytesLike,
    newVersion: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldRecordHash: string,
    newRecordHash: string,
    newVersion: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldRecordHash: string;
    newRecordHash: string;
    newVersion: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMedicalRecordRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IMedicalRecordRegistry;
  waitForDeployment(): Promise<this>;

  interface: IMedicalRecordRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRecord: TypedContractMethod<
    [recordHash: BytesLike],
    [IMedicalRecordRegistry.MedicalRecordStructOutput],
    "view"
  >;

  registerRecord: TypedContractMethod<
    [recordHash: BytesLike, patientHash: BytesLike],
    [void],
    "nonpayable"
  >;

  updateVersion: TypedContractMethod<
    [oldRecordHash: BytesLike, newRecordHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyRecord: TypedContractMethod<
    [recordHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [recordHash: BytesLike],
    [IMedicalRecordRegistry.MedicalRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerRecord"
  ): TypedContractMethod<
    [recordHash: BytesLike, patientHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateVersion"
  ): TypedContractMethod<
    [oldRecordHash: BytesLike, newRecordHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyRecord"
  ): TypedContractMethod<[recordHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "RecordRegistered"
  ): TypedContractEvent<
    RecordRegisteredEvent.InputTuple,
    RecordRegisteredEvent.OutputTuple,
    RecordRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RecordVerified"
  ): TypedContractEvent<
    RecordVerifiedEvent.InputTuple,
    RecordVerifiedEvent.OutputTuple,
    RecordVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RecordVersionUpdated"
  ): TypedContractEvent<
    RecordVersionUpdatedEvent.InputTuple,
    RecordVersionUpdatedEvent.OutputTuple,
    RecordVersionUpdatedEvent.OutputObject
  >;

  filters: {
    "RecordRegistered(bytes32,bytes32,address,uint32,uint256)": TypedContractEvent<
      RecordRegisteredEvent.InputTuple,
      RecordRegisteredEvent.OutputTuple,
      RecordRegisteredEvent.OutputObject
    >;
    RecordRegistered: TypedContractEvent<
      RecordRegisteredEvent.InputTuple,
      RecordRegisteredEvent.OutputTuple,
      RecordRegisteredEvent.OutputObject
    >;

    "RecordVerified(bytes32,uint256)": TypedContractEvent<
      RecordVerifiedEvent.InputTuple,
      RecordVerifiedEvent.OutputTuple,
      RecordVerifiedEvent.OutputObject
    >;
    RecordVerified: TypedContractEvent<
      RecordVerifiedEvent.InputTuple,
      RecordVerifiedEvent.OutputTuple,
      RecordVerifiedEvent.OutputObject
    >;

    "RecordVersionUpdated(bytes32,bytes32,uint32,uint256)": TypedContractEvent<
      RecordVersionUpdatedEvent.InputTuple,
      RecordVersionUpdatedEvent.OutputTuple,
      RecordVersionUpdatedEvent.OutputObject
    >;
    RecordVersionUpdated: TypedContractEvent<
      RecordVersionUpdatedEvent.InputTuple,
      RecordVersionUpdatedEvent.OutputTuple,
      RecordVersionUpdatedEvent.OutputObject
    >;
  };
}
