/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuditTrail } from "./IAuditTrail";
export type { IDoctorRegistry } from "./IDoctorRegistry";
export type { IMedicalRecordRegistry } from "./IMedicalRecordRegistry";
export type { IPatientRegistry } from "./IPatientRegistry";
export type { IPharmacyRegistry } from "./IPharmacyRegistry";
export type { IPrescriptionRegistry } from "./IPrescriptionRegistry";
