/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPatientRegistry {
  export type PatientStruct = {
    wallet: AddressLike;
    createdTimestamp: BigNumberish;
    updatedTimestamp: BigNumberish;
    isVerified: boolean;
    isActive: boolean;
  };

  export type PatientStructOutput = [
    wallet: string,
    createdTimestamp: bigint,
    updatedTimestamp: bigint,
    isVerified: boolean,
    isActive: boolean
  ] & {
    wallet: string;
    createdTimestamp: bigint;
    updatedTimestamp: bigint;
    isVerified: boolean;
    isActive: boolean;
  };
}

export interface IPatientRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivatePatient"
      | "getPatient"
      | "reactivatePatient"
      | "registerPatient"
      | "updateWallet"
      | "verifyPatient"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PatientDeactivated"
      | "PatientReactivated"
      | "PatientRegistered"
      | "PatientVerified"
      | "PatientWalletUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivatePatient",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatient",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivatePatient",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPatient",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWallet",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPatient",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivatePatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPatient", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivatePatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPatient",
    data: BytesLike
  ): Result;
}

export namespace PatientDeactivatedEvent {
  export type InputTuple = [patientHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [patientHash: string, timestamp: bigint];
  export interface OutputObject {
    patientHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientReactivatedEvent {
  export type InputTuple = [patientHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [patientHash: string, timestamp: bigint];
  export interface OutputObject {
    patientHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientRegisteredEvent {
  export type InputTuple = [
    patientHash: BytesLike,
    wallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patientHash: string,
    wallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patientHash: string;
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientVerifiedEvent {
  export type InputTuple = [patientHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [patientHash: string, timestamp: bigint];
  export interface OutputObject {
    patientHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientWalletUpdatedEvent {
  export type InputTuple = [
    patientHash: BytesLike,
    newWallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patientHash: string,
    newWallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patientHash: string;
    newWallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPatientRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPatientRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPatientRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivatePatient: TypedContractMethod<
    [patientHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getPatient: TypedContractMethod<
    [patientHash: BytesLike],
    [IPatientRegistry.PatientStructOutput],
    "view"
  >;

  reactivatePatient: TypedContractMethod<
    [patientHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerPatient: TypedContractMethod<
    [patientHash: BytesLike, wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWallet: TypedContractMethod<
    [patientHash: BytesLike, newWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyPatient: TypedContractMethod<
    [patientHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivatePatient"
  ): TypedContractMethod<[patientHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPatient"
  ): TypedContractMethod<
    [patientHash: BytesLike],
    [IPatientRegistry.PatientStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivatePatient"
  ): TypedContractMethod<[patientHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerPatient"
  ): TypedContractMethod<
    [patientHash: BytesLike, wallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateWallet"
  ): TypedContractMethod<
    [patientHash: BytesLike, newWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyPatient"
  ): TypedContractMethod<[patientHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "PatientDeactivated"
  ): TypedContractEvent<
    PatientDeactivatedEvent.InputTuple,
    PatientDeactivatedEvent.OutputTuple,
    PatientDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PatientReactivated"
  ): TypedContractEvent<
    PatientReactivatedEvent.InputTuple,
    PatientReactivatedEvent.OutputTuple,
    PatientReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PatientRegistered"
  ): TypedContractEvent<
    PatientRegisteredEvent.InputTuple,
    PatientRegisteredEvent.OutputTuple,
    PatientRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PatientVerified"
  ): TypedContractEvent<
    PatientVerifiedEvent.InputTuple,
    PatientVerifiedEvent.OutputTuple,
    PatientVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "PatientWalletUpdated"
  ): TypedContractEvent<
    PatientWalletUpdatedEvent.InputTuple,
    PatientWalletUpdatedEvent.OutputTuple,
    PatientWalletUpdatedEvent.OutputObject
  >;

  filters: {
    "PatientDeactivated(bytes32,uint256)": TypedContractEvent<
      PatientDeactivatedEvent.InputTuple,
      PatientDeactivatedEvent.OutputTuple,
      PatientDeactivatedEvent.OutputObject
    >;
    PatientDeactivated: TypedContractEvent<
      PatientDeactivatedEvent.InputTuple,
      PatientDeactivatedEvent.OutputTuple,
      PatientDeactivatedEvent.OutputObject
    >;

    "PatientReactivated(bytes32,uint256)": TypedContractEvent<
      PatientReactivatedEvent.InputTuple,
      PatientReactivatedEvent.OutputTuple,
      PatientReactivatedEvent.OutputObject
    >;
    PatientReactivated: TypedContractEvent<
      PatientReactivatedEvent.InputTuple,
      PatientReactivatedEvent.OutputTuple,
      PatientReactivatedEvent.OutputObject
    >;

    "PatientRegistered(bytes32,address,uint256)": TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;
    PatientRegistered: TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;

    "PatientVerified(bytes32,uint256)": TypedContractEvent<
      PatientVerifiedEvent.InputTuple,
      PatientVerifiedEvent.OutputTuple,
      PatientVerifiedEvent.OutputObject
    >;
    PatientVerified: TypedContractEvent<
      PatientVerifiedEvent.InputTuple,
      PatientVerifiedEvent.OutputTuple,
      PatientVerifiedEvent.OutputObject
    >;

    "PatientWalletUpdated(bytes32,address,uint256)": TypedContractEvent<
      PatientWalletUpdatedEvent.InputTuple,
      PatientWalletUpdatedEvent.OutputTuple,
      PatientWalletUpdatedEvent.OutputObject
    >;
    PatientWalletUpdated: TypedContractEvent<
      PatientWalletUpdatedEvent.InputTuple,
      PatientWalletUpdatedEvent.OutputTuple,
      PatientWalletUpdatedEvent.OutputObject
    >;
  };
}
