/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPharmacyRegistry {
  export type PharmacyStruct = {
    licenseHash: BytesLike;
    owner: AddressLike;
    createdTimestamp: BigNumberish;
    updatedTimestamp: BigNumberish;
    isVerified: boolean;
    isSuspended: boolean;
  };

  export type PharmacyStructOutput = [
    licenseHash: string,
    owner: string,
    createdTimestamp: bigint,
    updatedTimestamp: bigint,
    isVerified: boolean,
    isSuspended: boolean
  ] & {
    licenseHash: string;
    owner: string;
    createdTimestamp: bigint;
    updatedTimestamp: bigint;
    isVerified: boolean;
    isSuspended: boolean;
  };
}

export interface IPharmacyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPharmacy"
      | "reactivatePharmacy"
      | "registerPharmacy"
      | "suspendPharmacy"
      | "verifyPharmacy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PharmacyReactivated"
      | "PharmacyRegistered"
      | "PharmacySuspended"
      | "PharmacyVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getPharmacy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivatePharmacy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPharmacy",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendPharmacy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPharmacy",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivatePharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPharmacy",
    data: BytesLike
  ): Result;
}

export namespace PharmacyReactivatedEvent {
  export type InputTuple = [pharmacyHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [pharmacyHash: string, timestamp: bigint];
  export interface OutputObject {
    pharmacyHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PharmacyRegisteredEvent {
  export type InputTuple = [
    pharmacyHash: BytesLike,
    licenseHash: BytesLike,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    pharmacyHash: string,
    licenseHash: string,
    owner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    pharmacyHash: string;
    licenseHash: string;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PharmacySuspendedEvent {
  export type InputTuple = [pharmacyHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [pharmacyHash: string, timestamp: bigint];
  export interface OutputObject {
    pharmacyHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PharmacyVerifiedEvent {
  export type InputTuple = [pharmacyHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [pharmacyHash: string, timestamp: bigint];
  export interface OutputObject {
    pharmacyHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPharmacyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPharmacyRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPharmacyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPharmacy: TypedContractMethod<
    [pharmacyHash: BytesLike],
    [IPharmacyRegistry.PharmacyStructOutput],
    "view"
  >;

  reactivatePharmacy: TypedContractMethod<
    [pharmacyHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerPharmacy: TypedContractMethod<
    [pharmacyHash: BytesLike, licenseHash: BytesLike, owner: AddressLike],
    [void],
    "nonpayable"
  >;

  suspendPharmacy: TypedContractMethod<
    [pharmacyHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyPharmacy: TypedContractMethod<
    [pharmacyHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPharmacy"
  ): TypedContractMethod<
    [pharmacyHash: BytesLike],
    [IPharmacyRegistry.PharmacyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivatePharmacy"
  ): TypedContractMethod<[pharmacyHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerPharmacy"
  ): TypedContractMethod<
    [pharmacyHash: BytesLike, licenseHash: BytesLike, owner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "suspendPharmacy"
  ): TypedContractMethod<[pharmacyHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyPharmacy"
  ): TypedContractMethod<[pharmacyHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "PharmacyReactivated"
  ): TypedContractEvent<
    PharmacyReactivatedEvent.InputTuple,
    PharmacyReactivatedEvent.OutputTuple,
    PharmacyReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PharmacyRegistered"
  ): TypedContractEvent<
    PharmacyRegisteredEvent.InputTuple,
    PharmacyRegisteredEvent.OutputTuple,
    PharmacyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PharmacySuspended"
  ): TypedContractEvent<
    PharmacySuspendedEvent.InputTuple,
    PharmacySuspendedEvent.OutputTuple,
    PharmacySuspendedEvent.OutputObject
  >;
  getEvent(
    key: "PharmacyVerified"
  ): TypedContractEvent<
    PharmacyVerifiedEvent.InputTuple,
    PharmacyVerifiedEvent.OutputTuple,
    PharmacyVerifiedEvent.OutputObject
  >;

  filters: {
    "PharmacyReactivated(bytes32,uint256)": TypedContractEvent<
      PharmacyReactivatedEvent.InputTuple,
      PharmacyReactivatedEvent.OutputTuple,
      PharmacyReactivatedEvent.OutputObject
    >;
    PharmacyReactivated: TypedContractEvent<
      PharmacyReactivatedEvent.InputTuple,
      PharmacyReactivatedEvent.OutputTuple,
      PharmacyReactivatedEvent.OutputObject
    >;

    "PharmacyRegistered(bytes32,bytes32,address,uint256)": TypedContractEvent<
      PharmacyRegisteredEvent.InputTuple,
      PharmacyRegisteredEvent.OutputTuple,
      PharmacyRegisteredEvent.OutputObject
    >;
    PharmacyRegistered: TypedContractEvent<
      PharmacyRegisteredEvent.InputTuple,
      PharmacyRegisteredEvent.OutputTuple,
      PharmacyRegisteredEvent.OutputObject
    >;

    "PharmacySuspended(bytes32,uint256)": TypedContractEvent<
      PharmacySuspendedEvent.InputTuple,
      PharmacySuspendedEvent.OutputTuple,
      PharmacySuspendedEvent.OutputObject
    >;
    PharmacySuspended: TypedContractEvent<
      PharmacySuspendedEvent.InputTuple,
      PharmacySuspendedEvent.OutputTuple,
      PharmacySuspendedEvent.OutputObject
    >;

    "PharmacyVerified(bytes32,uint256)": TypedContractEvent<
      PharmacyVerifiedEvent.InputTuple,
      PharmacyVerifiedEvent.OutputTuple,
      PharmacyVerifiedEvent.OutputObject
    >;
    PharmacyVerified: TypedContractEvent<
      PharmacyVerifiedEvent.InputTuple,
      PharmacyVerifiedEvent.OutputTuple,
      PharmacyVerifiedEvent.OutputObject
    >;
  };
}
