/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPrescriptionRegistry {
  export type PrescriptionStruct = {
    patientHash: BytesLike;
    doctorHash: BytesLike;
    creator: AddressLike;
    timestamp: BigNumberish;
    version: BigNumberish;
    isRevoked: boolean;
    isVerified: boolean;
  };

  export type PrescriptionStructOutput = [
    patientHash: string,
    doctorHash: string,
    creator: string,
    timestamp: bigint,
    version: bigint,
    isRevoked: boolean,
    isVerified: boolean
  ] & {
    patientHash: string;
    doctorHash: string;
    creator: string;
    timestamp: bigint;
    version: bigint;
    isRevoked: boolean;
    isVerified: boolean;
  };
}

export interface IPrescriptionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPrescription"
      | "getPrescription"
      | "revokePrescription"
      | "updateVersion"
      | "verifyPrescription"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PrescriptionCreated"
      | "PrescriptionRevoked"
      | "PrescriptionVerified"
      | "PrescriptionVersionUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createPrescription",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrescription",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokePrescription",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVersion",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPrescription",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPrescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokePrescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPrescription",
    data: BytesLike
  ): Result;
}

export namespace PrescriptionCreatedEvent {
  export type InputTuple = [
    prescriptionHash: BytesLike,
    patientHash: BytesLike,
    doctorHash: BytesLike,
    version: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    prescriptionHash: string,
    patientHash: string,
    doctorHash: string,
    version: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    prescriptionHash: string;
    patientHash: string;
    doctorHash: string;
    version: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrescriptionRevokedEvent {
  export type InputTuple = [
    prescriptionHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [prescriptionHash: string, timestamp: bigint];
  export interface OutputObject {
    prescriptionHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrescriptionVerifiedEvent {
  export type InputTuple = [
    prescriptionHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [prescriptionHash: string, timestamp: bigint];
  export interface OutputObject {
    prescriptionHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrescriptionVersionUpdatedEvent {
  export type InputTuple = [
    oldPrescriptionHash: BytesLike,
    newPrescriptionHash: BytesLike,
    newVersion: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldPrescriptionHash: string,
    newPrescriptionHash: string,
    newVersion: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldPrescriptionHash: string;
    newPrescriptionHash: string;
    newVersion: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPrescriptionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPrescriptionRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPrescriptionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPrescription: TypedContractMethod<
    [
      prescriptionHash: BytesLike,
      patientHash: BytesLike,
      doctorHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getPrescription: TypedContractMethod<
    [prescriptionHash: BytesLike],
    [IPrescriptionRegistry.PrescriptionStructOutput],
    "view"
  >;

  revokePrescription: TypedContractMethod<
    [prescriptionHash: BytesLike],
    [void],
    "nonpayable"
  >;

  updateVersion: TypedContractMethod<
    [oldPrescriptionHash: BytesLike, newPrescriptionHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyPrescription: TypedContractMethod<
    [prescriptionHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPrescription"
  ): TypedContractMethod<
    [
      prescriptionHash: BytesLike,
      patientHash: BytesLike,
      doctorHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPrescription"
  ): TypedContractMethod<
    [prescriptionHash: BytesLike],
    [IPrescriptionRegistry.PrescriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokePrescription"
  ): TypedContractMethod<[prescriptionHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVersion"
  ): TypedContractMethod<
    [oldPrescriptionHash: BytesLike, newPrescriptionHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyPrescription"
  ): TypedContractMethod<[prescriptionHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "PrescriptionCreated"
  ): TypedContractEvent<
    PrescriptionCreatedEvent.InputTuple,
    PrescriptionCreatedEvent.OutputTuple,
    PrescriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PrescriptionRevoked"
  ): TypedContractEvent<
    PrescriptionRevokedEvent.InputTuple,
    PrescriptionRevokedEvent.OutputTuple,
    PrescriptionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "PrescriptionVerified"
  ): TypedContractEvent<
    PrescriptionVerifiedEvent.InputTuple,
    PrescriptionVerifiedEvent.OutputTuple,
    PrescriptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "PrescriptionVersionUpdated"
  ): TypedContractEvent<
    PrescriptionVersionUpdatedEvent.InputTuple,
    PrescriptionVersionUpdatedEvent.OutputTuple,
    PrescriptionVersionUpdatedEvent.OutputObject
  >;

  filters: {
    "PrescriptionCreated(bytes32,bytes32,bytes32,uint32,uint256)": TypedContractEvent<
      PrescriptionCreatedEvent.InputTuple,
      PrescriptionCreatedEvent.OutputTuple,
      PrescriptionCreatedEvent.OutputObject
    >;
    PrescriptionCreated: TypedContractEvent<
      PrescriptionCreatedEvent.InputTuple,
      PrescriptionCreatedEvent.OutputTuple,
      PrescriptionCreatedEvent.OutputObject
    >;

    "PrescriptionRevoked(bytes32,uint256)": TypedContractEvent<
      PrescriptionRevokedEvent.InputTuple,
      PrescriptionRevokedEvent.OutputTuple,
      PrescriptionRevokedEvent.OutputObject
    >;
    PrescriptionRevoked: TypedContractEvent<
      PrescriptionRevokedEvent.InputTuple,
      PrescriptionRevokedEvent.OutputTuple,
      PrescriptionRevokedEvent.OutputObject
    >;

    "PrescriptionVerified(bytes32,uint256)": TypedContractEvent<
      PrescriptionVerifiedEvent.InputTuple,
      PrescriptionVerifiedEvent.OutputTuple,
      PrescriptionVerifiedEvent.OutputObject
    >;
    PrescriptionVerified: TypedContractEvent<
      PrescriptionVerifiedEvent.InputTuple,
      PrescriptionVerifiedEvent.OutputTuple,
      PrescriptionVerifiedEvent.OutputObject
    >;

    "PrescriptionVersionUpdated(bytes32,bytes32,uint32,uint256)": TypedContractEvent<
      PrescriptionVersionUpdatedEvent.InputTuple,
      PrescriptionVersionUpdatedEvent.OutputTuple,
      PrescriptionVersionUpdatedEvent.OutputObject
    >;
    PrescriptionVersionUpdated: TypedContractEvent<
      PrescriptionVersionUpdatedEvent.InputTuple,
      PrescriptionVersionUpdatedEvent.OutputTuple,
      PrescriptionVersionUpdatedEvent.OutputObject
    >;
  };
}
