/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DoctorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BACKEND_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "approveDoctor"
      | "doctors"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "reactivateDoctor"
      | "registerDoctor"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "suspendDoctor"
      | "verifyDoctorStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DoctorApproved"
      | "DoctorReactivated"
      | "DoctorRegistered"
      | "DoctorSuspended"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BACKEND_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveDoctor",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "doctors", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateDoctor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDoctor",
    values: [string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendDoctor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDoctorStatus",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "BACKEND_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doctors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDoctorStatus",
    data: BytesLike
  ): Result;
}

export namespace DoctorApprovedEvent {
  export type InputTuple = [doctorId: string, timestamp: BigNumberish];
  export type OutputTuple = [doctorId: string, timestamp: bigint];
  export interface OutputObject {
    doctorId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorReactivatedEvent {
  export type InputTuple = [doctorId: string];
  export type OutputTuple = [doctorId: string];
  export interface OutputObject {
    doctorId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorRegisteredEvent {
  export type InputTuple = [
    doctorId: string,
    wallet: AddressLike,
    licenseHash: string
  ];
  export type OutputTuple = [
    doctorId: string,
    wallet: string,
    licenseHash: string
  ];
  export interface OutputObject {
    doctorId: string;
    wallet: string;
    licenseHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorSuspendedEvent {
  export type InputTuple = [doctorId: string];
  export type OutputTuple = [doctorId: string];
  export interface OutputObject {
    doctorId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DoctorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DoctorRegistry;
  waitForDeployment(): Promise<this>;

  interface: DoctorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BACKEND_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  approveDoctor: TypedContractMethod<[doctorId: string], [void], "nonpayable">;

  doctors: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, boolean, bigint] & {
        doctorId: string;
        wallet: string;
        licenseHash: string;
        isVerified: boolean;
        isSuspended: boolean;
        approvalTimestamp: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  reactivateDoctor: TypedContractMethod<
    [doctorId: string],
    [void],
    "nonpayable"
  >;

  registerDoctor: TypedContractMethod<
    [doctorId: string, wallet: AddressLike, licenseHash: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  suspendDoctor: TypedContractMethod<[doctorId: string], [void], "nonpayable">;

  verifyDoctorStatus: TypedContractMethod<
    [doctorId: string],
    [[boolean, boolean] & { isVerified: boolean; isSuspended: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BACKEND_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveDoctor"
  ): TypedContractMethod<[doctorId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "doctors"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, boolean, bigint] & {
        doctorId: string;
        wallet: string;
        licenseHash: string;
        isVerified: boolean;
        isSuspended: boolean;
        approvalTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivateDoctor"
  ): TypedContractMethod<[doctorId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerDoctor"
  ): TypedContractMethod<
    [doctorId: string, wallet: AddressLike, licenseHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "suspendDoctor"
  ): TypedContractMethod<[doctorId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDoctorStatus"
  ): TypedContractMethod<
    [doctorId: string],
    [[boolean, boolean] & { isVerified: boolean; isSuspended: boolean }],
    "view"
  >;

  getEvent(
    key: "DoctorApproved"
  ): TypedContractEvent<
    DoctorApprovedEvent.InputTuple,
    DoctorApprovedEvent.OutputTuple,
    DoctorApprovedEvent.OutputObject
  >;
  getEvent(
    key: "DoctorReactivated"
  ): TypedContractEvent<
    DoctorReactivatedEvent.InputTuple,
    DoctorReactivatedEvent.OutputTuple,
    DoctorReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "DoctorRegistered"
  ): TypedContractEvent<
    DoctorRegisteredEvent.InputTuple,
    DoctorRegisteredEvent.OutputTuple,
    DoctorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DoctorSuspended"
  ): TypedContractEvent<
    DoctorSuspendedEvent.InputTuple,
    DoctorSuspendedEvent.OutputTuple,
    DoctorSuspendedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "DoctorApproved(string,uint256)": TypedContractEvent<
      DoctorApprovedEvent.InputTuple,
      DoctorApprovedEvent.OutputTuple,
      DoctorApprovedEvent.OutputObject
    >;
    DoctorApproved: TypedContractEvent<
      DoctorApprovedEvent.InputTuple,
      DoctorApprovedEvent.OutputTuple,
      DoctorApprovedEvent.OutputObject
    >;

    "DoctorReactivated(string)": TypedContractEvent<
      DoctorReactivatedEvent.InputTuple,
      DoctorReactivatedEvent.OutputTuple,
      DoctorReactivatedEvent.OutputObject
    >;
    DoctorReactivated: TypedContractEvent<
      DoctorReactivatedEvent.InputTuple,
      DoctorReactivatedEvent.OutputTuple,
      DoctorReactivatedEvent.OutputObject
    >;

    "DoctorRegistered(string,address,string)": TypedContractEvent<
      DoctorRegisteredEvent.InputTuple,
      DoctorRegisteredEvent.OutputTuple,
      DoctorRegisteredEvent.OutputObject
    >;
    DoctorRegistered: TypedContractEvent<
      DoctorRegisteredEvent.InputTuple,
      DoctorRegisteredEvent.OutputTuple,
      DoctorRegisteredEvent.OutputObject
    >;

    "DoctorSuspended(string)": TypedContractEvent<
      DoctorSuspendedEvent.InputTuple,
      DoctorSuspendedEvent.OutputTuple,
      DoctorSuspendedEvent.OutputObject
    >;
    DoctorSuspended: TypedContractEvent<
      DoctorSuspendedEvent.InputTuple,
      DoctorSuspendedEvent.OutputTuple,
      DoctorSuspendedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
