/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuditTrail,
  IAuditTrailInterface,
} from "../../../contracts/interfaces/IAuditTrail";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "eventType",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "entityHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "AuditEventLogged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "eventType",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "entityHash",
        type: "bytes32",
      },
    ],
    name: "logEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAuditTrail__factory {
  static readonly abi = _abi;
  static createInterface(): IAuditTrailInterface {
    return new Interface(_abi) as IAuditTrailInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAuditTrail {
    return new Contract(address, _abi, runner) as unknown as IAuditTrail;
  }
}
