/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMedicalRecordRegistry,
  IMedicalRecordRegistryInterface,
} from "../../../contracts/interfaces/IMedicalRecordRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "recordHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "patientHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "uploader",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "version",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "RecordRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "recordHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "RecordVerified",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "oldRecordHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newRecordHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newVersion",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "RecordVersionUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordHash",
        type: "bytes32",
      },
    ],
    name: "getRecord",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "patientHash",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "uploader",
            type: "address",
          },
          {
            internalType: "uint40",
            name: "timestamp",
            type: "uint40",
          },
          {
            internalType: "uint32",
            name: "version",
            type: "uint32",
          },
          {
            internalType: "bool",
            name: "isVerified",
            type: "bool",
          },
        ],
        internalType: "struct IMedicalRecordRegistry.MedicalRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "patientHash",
        type: "bytes32",
      },
    ],
    name: "registerRecord",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "oldRecordHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newRecordHash",
        type: "bytes32",
      },
    ],
    name: "updateVersion",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordHash",
        type: "bytes32",
      },
    ],
    name: "verifyRecord",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMedicalRecordRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IMedicalRecordRegistryInterface {
    return new Interface(_abi) as IMedicalRecordRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMedicalRecordRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMedicalRecordRegistry;
  }
}
