/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAuditTrail__factory } from "./IAuditTrail__factory";
export { IDoctorRegistry__factory } from "./IDoctorRegistry__factory";
export { IMedicalRecordRegistry__factory } from "./IMedicalRecordRegistry__factory";
export { IPatientRegistry__factory } from "./IPatientRegistry__factory";
export { IPharmacyRegistry__factory } from "./IPharmacyRegistry__factory";
export { IPrescriptionRegistry__factory } from "./IPrescriptionRegistry__factory";
