/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPharmacyRegistry,
  IPharmacyRegistryInterface,
} from "../../../contracts/interfaces/IPharmacyRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "pharmacyHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PharmacyReactivated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "pharmacyHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "licenseHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PharmacyRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "pharmacyHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PharmacySuspended",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "pharmacyHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PharmacyVerified",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "pharmacyHash",
        type: "bytes32",
      },
    ],
    name: "getPharmacy",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "licenseHash",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint40",
            name: "createdTimestamp",
            type: "uint40",
          },
          {
            internalType: "uint40",
            name: "updatedTimestamp",
            type: "uint40",
          },
          {
            internalType: "bool",
            name: "isVerified",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isSuspended",
            type: "bool",
          },
        ],
        internalType: "struct IPharmacyRegistry.Pharmacy",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "pharmacyHash",
        type: "bytes32",
      },
    ],
    name: "reactivatePharmacy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "pharmacyHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "licenseHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "registerPharmacy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "pharmacyHash",
        type: "bytes32",
      },
    ],
    name: "suspendPharmacy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "pharmacyHash",
        type: "bytes32",
      },
    ],
    name: "verifyPharmacy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPharmacyRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPharmacyRegistryInterface {
    return new Interface(_abi) as IPharmacyRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPharmacyRegistry {
    return new Contract(address, _abi, runner) as unknown as IPharmacyRegistry;
  }
}
