/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPrescriptionRegistry,
  IPrescriptionRegistryInterface,
} from "../../../contracts/interfaces/IPrescriptionRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "prescriptionHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "patientHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "doctorHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "version",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PrescriptionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "prescriptionHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PrescriptionRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "prescriptionHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PrescriptionVerified",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "oldPrescriptionHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newPrescriptionHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newVersion",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PrescriptionVersionUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "prescriptionHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "patientHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "doctorHash",
        type: "bytes32",
      },
    ],
    name: "createPrescription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "prescriptionHash",
        type: "bytes32",
      },
    ],
    name: "getPrescription",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "patientHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "doctorHash",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            internalType: "uint40",
            name: "timestamp",
            type: "uint40",
          },
          {
            internalType: "uint32",
            name: "version",
            type: "uint32",
          },
          {
            internalType: "bool",
            name: "isRevoked",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isVerified",
            type: "bool",
          },
        ],
        internalType: "struct IPrescriptionRegistry.Prescription",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "prescriptionHash",
        type: "bytes32",
      },
    ],
    name: "revokePrescription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "oldPrescriptionHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newPrescriptionHash",
        type: "bytes32",
      },
    ],
    name: "updateVersion",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "prescriptionHash",
        type: "bytes32",
      },
    ],
    name: "verifyPrescription",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPrescriptionRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPrescriptionRegistryInterface {
    return new Interface(_abi) as IPrescriptionRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPrescriptionRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPrescriptionRegistry;
  }
}
