/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AuditTrail__factory } from "./AuditTrail__factory";
export { DoctorRegistry__factory } from "./DoctorRegistry__factory";
export { MedicalRecordRegistry__factory } from "./MedicalRecordRegistry__factory";
export { PatientRegistry__factory } from "./PatientRegistry__factory";
export { PharmacyRegistry__factory } from "./PharmacyRegistry__factory";
export { PrescriptionRegistry__factory } from "./PrescriptionRegistry__factory";
